### ISSUE TITLE
HI, This plugin does not seem to work properly, Please check this link below

### ISSUE THREAD

**Issue by xmyhhh** [kuhnchris/vscode-formatter-godot#1]
https://github.com/godotengine/godot-vscode-plugin/issues/390

**Comment by kuhnchris** [comment]
Hi, thanks, replied there, apparently the gdtoolkit isn't available.

**Comment by EddieDover** [comment]
The screenshots from the link looks exactly like what myself and the author of Issue #2 have seen.
I've issued a PR #3 that fixes the problem.
